scripts:
      - name: Repair and Create Project
        script: |
          flutter create . --platforms android --project-name keuangan_ree
      - name: Generate App Icons
        script: |
          flutter pub get
          dart run flutter_launcher_icons
      - name: Change App Display Name
        script: |
          export APP_NAME="Keuangan Ree"
          perl -pi -e 's/android:label=".*?"/android:label="'"$APP_NAME"'"/g' android/app/src/main/AndroidManifest.xml
      - name: Build APK
        script: flutter build apk --release
